name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: test
      run: |
        mkdir build && cd build
        autoreconf --install ..
        ../configure
        make
        ./procurator-test
